import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {handleApi} from '../server/api.mjs';import {openDB} from '../scripts/sqlite-adapter.mjs';
const origin='https://counsel.example';const adminToken='test-only-administrator-token-32-characters';
const day=new Date(Date.now()+2*86400000).toISOString().slice(0,10);
function setup(){const env={DB:openDB(),AUTH_MODE:'token',ADMIN_TOKEN:adminToken,PUBLIC_ORIGIN:origin,PRIVACY_RETENTION_TEXT:'테스트 보유 기간',PAYMENT_TERMS_TEXT:'테스트 환불 기준',TOSS_CLIENT_KEY:'test_ck_example',TOSS_SECRET_KEY:'test_sk_example'};return env;}
async function request(env,url,method='GET',body,headers={}){const req=new Request(origin+url,{method,headers:{Origin:origin,...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});const response=await handleApi(req,env);return {status:response.status,data:await response.json()};}
const ah={Authorization:'Bearer '+adminToken};
async function book(env,token='a'.repeat(64),branch='daegu'){return request(env,'/api/bookings','POST',{name:'테스트 신청자',phone:'010-0000-0000',branch,service:'개인 상담',preferredDate:day,preferredTime:'오전',consent:true,requestToken:token});}
async function confirm(env,b,time='10:00'){return request(env,'/api/admin/bookings/'+b.id,'PATCH',{status:'confirmed',scheduledDate:day,scheduledTime:time,amount:80000},ah);}
test('booking persistence, private access and retry idempotency',async()=>{const env=setup();const b=await book(env);assert.equal(b.status,201);assert.equal((await book(env)).data.id,b.data.id);assert.equal((await request(env,'/api/bookings/'+b.data.id)).status,404);const view=await request(env,'/api/bookings/'+b.data.id,'GET',null,{'X-Booking-Token':b.data.token});assert.equal(view.status,200);assert.equal(view.data.booking.name,undefined);assert.equal(view.data.booking.phone,undefined);assert.equal((await request(env,'/api/admin/bookings')).status,403);assert.equal((await request(env,'/api/admin/bookings','GET',null,{'oai-authenticated-user-email':'admin@example.com','oai-authenticated-user-id':'fake'})).status,403);env.DB.close();});
test('D1-compatible SQLite survives reopening',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'counsel-db-'));const file=path.join(dir,'test.sqlite');const env=setup();env.DB.close();env.DB=openDB(file);const b=await book(env);env.DB.close();env.DB=openDB(file);assert.equal((await request(env,'/api/bookings/'+b.data.id,'GET',null,{'X-Booking-Token':b.data.token})).status,200);env.DB.close();fs.rmSync(dir,{recursive:true});});
test('intake remains closed without disclosure; invalid inputs are rejected',async()=>{const env=setup();env.PRIVACY_RETENTION_TEXT='';assert.equal((await book(env)).status,503);env.PRIVACY_RETENTION_TEXT='test';const r=await request(env,'/api/bookings','POST',{consent:false});assert.equal(r.status,400);const cross=await request(env,'/api/admin/settings','POST',{privacyRetention:'x',paymentTerms:'y'},{...ah,Origin:'https://attacker.example'});assert.equal(cross.status,403);env.DB.close();});
test('confirmed slots are exclusive per branch',async()=>{const env=setup();const a=(await book(env)).data,b=(await book(env,'b'.repeat(64))).data,c=(await book(env,'c'.repeat(64),'uiseong')).data;assert.equal((await confirm(env,a)).status,200);assert.equal((await confirm(env,b)).status,409);assert.equal((await confirm(env,c)).status,200);env.DB.close();});
test('payment amount cannot be changed by customer; success requires provider',async()=>{const env=setup(),b=(await book(env)).data;await confirm(env,b);const headers={'X-Booking-Token':b.token};const order=(await request(env,`/api/bookings/${b.id}/order`,'POST',{},headers)).data;let calls=0;env.PAYMENT_FETCH=async(url,init)=>{calls++;return Response.json({status:'DONE',paymentKey:'payment-key',orderId:order.orderId,totalAmount:80000,currency:'KRW'});};assert.equal((await request(env,'/api/payments/confirm','POST',{bookingId:b.id,orderId:order.orderId,amount:1,paymentKey:'payment-key'},headers)).status,400);assert.equal(calls,0);const result=await request(env,'/api/payments/confirm','POST',{bookingId:b.id,orderId:order.orderId,amount:80000,paymentKey:'payment-key'},headers);assert.equal(result.data.status,'paid');assert.equal(calls,1);assert.equal((await request(env,'/api/payments/confirm','POST',{bookingId:b.id,orderId:order.orderId,amount:80000,paymentKey:'payment-key'},headers)).data.status,'paid');assert.equal(calls,1);assert.equal((await request(env,'/api/admin/bookings/'+b.id,'PATCH',{status:'cancelled'},ah)).status,409);env.DB.close();});
test('uncertain payment is not shown as paid; retry reconciles provider; refund verified',async()=>{const env=setup(),b=(await book(env)).data;await confirm(env,b);const headers={'X-Booking-Token':b.token};const o=(await request(env,`/api/bookings/${b.id}/order`,'POST',{},headers)).data;env.PAYMENT_FETCH=async()=>{throw Error('Timeout');};const payload={bookingId:b.id,orderId:o.orderId,amount:80000,paymentKey:'pkey'};assert.equal((await request(env,'/api/payments/confirm','POST',payload,headers)).status,503);assert.equal((await request(env,'/api/bookings/'+b.id,'GET',null,headers)).data.booking.payment_status,'unpaid');env.PAYMENT_FETCH=async()=>Response.json({status:'DONE',paymentKey:'pkey',orderId:o.orderId,totalAmount:80000,currency:'KRW'});assert.equal((await request(env,'/api/payments/confirm','POST',payload,headers)).data.status,'paid');env.PAYMENT_FETCH=async()=>Response.json({status:'CANCELED',paymentKey:'pkey',orderId:o.orderId,totalAmount:80000,currency:'KRW'});assert.equal((await request(env,`/api/admin/bookings/${b.id}/refund`,'POST',{confirm:true,reason:'테스트 취소'},ah)).data.status,'refunded');assert.equal((await request(env,'/api/bookings/'+b.id,'GET',null,headers)).data.booking.status,'cancelled');env.DB.close();});
test('price cannot change while an order is open',async()=>{const env=setup(),b=(await book(env)).data;await confirm(env,b);await request(env,`/api/bookings/${b.id}/order`,'POST',{}, {'X-Booking-Token':b.token});assert.equal((await confirm(env,b)).status,409);assert.equal((await request(env,`/api/admin/bookings/${b.id}/release-order`,'POST',{},ah)).status,200);assert.equal((await confirm(env,b)).status,200);env.DB.close();});
